### ISSUE TITLE
chkconfig needs to be removed

### ISSUE THREAD

**Issue by chasecbw** [bryanlittlefield/tugboat-php#39]
https://github.com/bryanlittlefield/tugboat-php/blob/e4b2ce302f18842f3467b77d72d295684cdb075e/Dockerfile#L65

Should be:
`RUN apt-get install -y git vim cron htop zip unzip pwgen curl wget ruby rubygems ruby-dev screen openssl openssh-server nano ncdu zsh`

**Comment by insanityfarm** [comment]
Looks like this was fixed by commit 88bef23.
