### ISSUE TITLE
These lines need to be swapped

### ISSUE THREAD

**Issue by chasecbw** [bryanlittlefield/tugboat-php#40]
https://github.com/bryanlittlefield/tugboat-php/blob/e4b2ce302f18842f3467b77d72d295684cdb075e/Dockerfile#L70-L71

The configuration isn't taking after installation. GD need to be configured before it's installed.

Should be:
`RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/`

Then:
`RUN docker-php-ext-install gd`

**Comment by insanityfarm** [comment]
Looks like this was fixed by commit 88bef23.
