### ISSUE TITLE
Not generating openssl key correctly

### ISSUE THREAD

**Issue by chasecbw** [bryanlittlefield/tugboat-php#41]
https://github.com/bryanlittlefield/tugboat-php/blob/e4b2ce302f18842f3467b77d72d295684cdb075e/Dockerfile#L113

Should be:
`RUN openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out server.pass.key`

**Comment by insanityfarm** [comment]
Looks like this was fixed by commit 88bef23.
